In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

In [3]:
intlist=list(range(10))
intlist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(intlist[0])

int

In [5]:
Stringlist=[str(index) for index in intlist]
Stringlist

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(Stringlist[0])

str

In [7]:
boolean=[True,False,True,False]
boolean

[True, False, True, False]

In [8]:
import array
array1=array.array('i',intlist)#i is to tell it an int
array1

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
nparray=np.array([1, 5, 4, 3, 2],dtype='float32')
nparray

array([1., 5., 4., 3., 2.], dtype=float32)

In [10]:
darray=np.array([(1, 5, 4), (3, 4, 5), (3, 1, 5)])
darray

array([[1, 5, 4],
       [3, 4, 5],
       [3, 1, 5]])

In [11]:
zero=np.zeros(5,dtype=int)#create an array with content of 0 and size of 5
zero

array([0, 0, 0, 0, 0])

In [12]:
one=np.ones((2,3),dtype=int)#create an array that have index 1 and datatype int
one

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
five=np.full((2,3),5)#create 2x3 array with index of 5
five

array([[5, 5, 5],
       [5, 5, 5]])

In [14]:
spacing=np.linspace(3,6,6)#value start from where and end where how many index it will divid each value equally
spacing

array([3. , 3.6, 4.2, 4.8, 5.4, 6. ])

In [15]:
random=np.random.random((2,3))#random.random let us take number between 0 to 1 and tell the array form
random

array([[0.03939784, 0.73287085, 0.21398075],
       [0.49814711, 0.42201113, 0.70888011]])

In [16]:
random2=np.random.randint(0,5,(2,3))
random2

array([[1, 1, 3],
       [3, 3, 2]])

In [17]:
meanstd=np.random.normal(0,1,(2,3))#mean and std and size check document for more ??
meanstd

array([[ 0.23558825,  1.7326713 ,  1.06251588],
       [ 0.83588021,  0.14141426, -0.13268713]])

In [18]:
arraymatrix=np.eye(3)
arraymatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
import numpy as np
infoarray=np.random.randint(10,size=(2,3))
print("ndim: ", infoarray.ndim)# how many dimension
print("shape:", infoarray.shape)#shape of the array like how many 2x3 or ?x? is it
print("size: ", infoarray.size)#how many index it have altogether
print("itemsize:", infoarray.itemsize)

ndim:  2
shape: (2, 3)
size:  6
itemsize: 4


In [20]:
# randnumarr=np.random.randint(1,10,(2,3),dtype=int)
# randnumarr(1,2)

In [21]:
arr2=np.array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])
arr2[:,1]

array([5, 6, 6])

In [22]:
arr2[0,:]

array([3, 5, 2, 4])

In [23]:
negarray=np.random.randint(1,10,(2,3))
negarray[0,-1]

2

In [24]:
random0to10=np.random.randint(0,10,10)
random0to10[:3]

array([4, 6, 0])

In [25]:
random0to10[4:]

array([1, 2, 3, 1, 9, 4])

In [26]:
random0to10[4:7]

array([1, 2, 3])

In [27]:
random0to10[11:0]

array([], dtype=int32)

In [28]:
7 in random0to10

False

In [29]:
np.flip(random0to10)

array([4, 9, 1, 3, 2, 1, 0, 0, 6, 4])

In [30]:
np.flip(random0to10[4:])

array([4, 9, 1, 3, 2, 1])

In [31]:
r=np.random.randint(0,10,(3,4))

In [32]:
r[:2,:3]

array([[8, 9, 2],
       [3, 4, 2]])

In [33]:
random0to10[1:4]

array([6, 0, 0])

In [34]:
r[:,0]

array([8, 3, 1])

In [35]:
r[0,:]

array([8, 9, 2, 9])

In [36]:
r.copy()

array([[8, 9, 2, 9],
       [3, 4, 2, 0],
       [1, 4, 9, 2]])

In [37]:
r[::-1,::-1]

array([[2, 9, 4, 1],
       [0, 2, 4, 3],
       [9, 2, 9, 8]])

In [38]:
array1=np.array([1,2,3,4])
array1[np.newaxis,:]

array([[1, 2, 3, 4]])

In [39]:
arr1=np.array([1,2,3])
arr2=np.array([1,3,4])
np.concatenate([arr1,arr2])

array([1, 2, 3, 1, 3, 4])

In [40]:
arr3=np.arange(0,10)

In [41]:
x1,x2,x3=np.split(arr3,[3,5])

In [42]:
x1,x2,x3

(array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9]))

In [43]:
np.sum(arr3)

45

In [44]:
np.add.reduce(arr3)

45

In [45]:
np.multiply.reduce(arr3)#use reduce to separate indexes

0

In [46]:
arr4=np.arange(0,7)

In [47]:
arr4

array([0, 1, 2, 3, 4, 5, 6])

In [48]:
np.multiply.outer(arr4,arr4)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  2,  4,  6,  8, 10, 12],
       [ 0,  3,  6,  9, 12, 15, 18],
       [ 0,  4,  8, 12, 16, 20, 24],
       [ 0,  5, 10, 15, 20, 25, 30],
       [ 0,  6, 12, 18, 24, 30, 36]])

In [49]:
arr5=np.random.randint(0,11,10)

In [50]:
print('sum: ',np.sum(arr5),'\n'#np.sum is faster than sum normal function
     'max: ',np.max(arr5),'\n',
     'min: ',np.min(arr5))

sum:  55 
max:  9 
 min:  0


In [51]:
arr6=np.random.randint(0,11,(2,3))

In [52]:
np.min(arr6[:,:])#find the minimum of all ndim in the array 

2

In [53]:
arr6.min(axis=0)#find for each column

array([2, 2, 2])

In [54]:
arr6.max(axis=0)#find for each column

array([ 3,  4, 10])

In [55]:
arr6.max(axis=1)#find for each row

array([ 4, 10])

In [56]:
arr7=np.ones((3,3))
a=np.array([0,1,2])

In [57]:
arr7+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [58]:
np.sum(arr6<6,axis=1)#number that less than 6 in each row

array([3, 2])

In [59]:
arr5[arr5>8]#number that greater than 8

array([9])

In [60]:
np.any(arr5>8)

True

In [61]:
#fancy index
rand=np.random.RandomState(42)
arr8=rand.randint(100,size=10)
arr8

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [62]:
[arr8[3],arr8[7],arr8[2]]

[71, 86, 14]

In [63]:
index=[3,7,4]
arr8[index]

array([71, 86, 60])

In [64]:
X=np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
row=np.array([0,1,2])
col=np.array([2,1,3])
X[row,col]

array([ 2,  5, 11])

In [66]:
X[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [67]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [68]:
X[2,[2,0,1]]

array([10,  8,  9])

In [69]:
import numpy as np
array=np.random.randint(1,10,(3,4))
array

array([[7, 8, 6, 4],
       [4, 8, 8, 9],
       [3, 9, 9, 7]])

In [70]:
np.max(array,axis=1)

array([8, 9, 9])

In [72]:
arr=np.array([1,2,34])
np.flip(arr)

array([34,  2,  1])